Clarify some env handling for pkg rules
ocaml/dune pull request #10455
Opened 2024-04-23 12:37 UTC by gridbugs

The logic for handling environments used when building packages is complicated. This change breaks it up into smaller functions, simplifies some of the logic, and adds some comments explaining what each one does.

A consequence of this change is that the order in which the bin directories of dependencies appear in the PATH variable while building a package is the same as the order in which the dependencies appear in the package's lockfile (previously the order was reversed).

---

This mostly consists of notes I made for myself and experimental changes I made to help me understand how this logic works. I think it's worth checking it in to help the next person better understand this code.

2024-04-23 20:53 UTC, rgrinberg approved these changes

2024-04-23 20:53 UTC, rgrinberg requested changes
LGTM, but the tests are failing

2024-04-24 11:51 UTC, gridbugs commented
Fixed a bug causing some variables to be concatenated rather than replaced in a situation where they should be replaced. I've promoted the failing test (opam-package-with-setenv) as the behaviour of dune after this change is closer to the behaviour of opam (confirmed by setting up some local opam packages matching the packages from this test). Dune's behaviour still doesn't perfectly match opam's because of https://github.com/ocaml/dune/issues/10440.

2024-04-24 19:27 UTC, rgrinberg approved these changes

2024-04-29 08:15 UTC, merged