pkg: build and make dev tools available (odoc, ocamlformat)
ocaml/dune pull request #10613
Opened 2024-06-05 15:08 UTC by moyodiallo

To avoid dune capturing a dev-tool like `odoc`, `ocamlformat` when using `dune build @doc` or `dune build @fmt`. This PR is about to build those tools independently from each other and from the dune-project dependencies, to avoid conflict. After a successful build of a dev-tool it will be directly available by the respective dune command. 

- [X] ocamlformat build and make it available
- [ ] ocamlformat stanza `(ocamlformat <version>)`
- [ ] odoc build and make it available
- [ ] prioritize `dev tools` to `PATH` when `dune.lock` dir is present in the project.
- [ ] add a cram test

2024-06-06 13:11 UTC, Leonidas-from-XIV requested changes
This is a great start! :tada: 

I've left some comments on on the code, but I think more important than that is to make sure the behaviour is what we want.

Personally I think, `ocamlformat` should not be locked when a user calls `dune pkg lock`. The issue here is that even if they never use it, they always have to pay the price for creating a lock file for ocamlformat. And if we extend this to Merlin, odoc, LSP-server, utop, the user might easily spend more time locking the dependencies of dev-tools they might never use than the dependencies of their own project.

As such I suggest changing the code to move the locking to before ocamlformat is invoked the first time, which is most likely part of the `@fmt` rule. When `@fmt` is called it would then attempt to lock & build if ocamlformat is not installed yet.

2024-06-06 15:46 UTC, moyodiallo commented
> Personally I think, `ocamlformat` should not be locked when a user calls `dune pkg lock`. The issue here is that even if they never use it, they always have to pay the price for creating a lock file for ocamlformat. And if we extend this to Merlin, odoc, LSP-server, utop, the user might easily spend more time locking the dependencies of dev-tools they might never use than the dependencies of their own project.
> 
> As such I suggest changing the code to move the locking to before ocamlformat is invoked the first time, which is most likely part of the `@fmt` rule. When `@fmt` is called it would then attempt to lock & build if ocamlformat is not installed yet.

This is more sensible, it is the direction that we need to follow, building a tool when needed.

2024-06-07 17:14 UTC, moyodiallo commented on src/dune_pkg/dev_tool.ml
> +let lock_dir = Path.Source.relative (Path.Source.of_string "dune.lock") "dev_tools.lock"
I suggest to do this in another PR to keep this one short and avoid having lot of changes.

2024-06-13 10:48 UTC, closed without merging

2024-06-13 10:49 UTC, moyodiallo commented
Closed to target for new PR #10647  that target `main` branch