melange: the compiler does not support -bin-annot-occurrences
ocaml/dune pull request #10622
Opened 2024-06-07 14:30 UTC by voodoos

The Melange compiler does not accept the `-bin-annot-occurrences` flag.

The test relying on OCaml's version is therefore incorrect when building with melange compiler.
This PR adds a special case to prevent use of this flag when building with melange.

2024-06-07 14:32 UTC, emillon commented
cc @anmonteiro - do we want this, or fix this on the melange side?
(@gridbugs we might need to backport this to 3.16 if we go with the patch route)

2024-06-07 18:02 UTC, anmonteiro commented
We’ll have to fix it in both sides I suppose. Where can I read more about this flag?

2024-06-07 19:50 UTC, rgrinberg requested changes

2024-06-07 19:50 UTC, rgrinberg commented on src/dune_rules/module_compilation.ml
> +         then [ "-bin-annot"; "-bin-annot-occurrences" ]
spurious change? the previous version did not duplicate the flag name here

2024-06-07 19:50 UTC, rgrinberg commented on src/dune_rules/module_compilation.ml
> -           if Version.supports_bin_annot_occurrences ocaml.version
How about just maintaining the old code but introducing:

```
let supports_bin_annot_occurences = Version.supports_bin_annot_occurences ocaml.version && not cm_kind <> Melange in
```

2024-06-08 03:36 UTC, anmonteiro commented
actually, since melange supports 5.2, this is just a matter of supporting the flag. 

I bet it'd be nice to have occurrences support in Melange projects, too, so let me release a Melange version with support for this flag.

2024-06-08 05:37 UTC, anmonteiro commented
released melange 4.0.1-52 with this change: https://github.com/ocaml/opam-repository/pull/26043

2024-06-10 09:13 UTC, voodoos commented
Thanks @anmonteiro

I guess that means this PR is no more useful ?

2024-06-10 16:58 UTC, anmonteiro commented
I’d vote to close it

2024-06-10 17:09 UTC, closed without merging