Add repro for gh10741
ocaml/dune pull request #10742
Opened 2024-07-18 07:14 UTC by gridbugs

Repro for https://github.com/ocaml/dune/issues/10741

2024-07-19 07:23 UTC, moyodiallo approved these changes

2024-07-19 07:23 UTC, moyodiallo commented on test/blackbox-tests/test-cases/pkg/oneshot-webserver-large-file-curl-error.t
> +  $ dd if=/dev/zero of=./large-file iflag=fullblock,count_bytes status=none count=20M
I have tested on my machine, and it starts failing from 14M, yeah 20M could be better number.

2024-07-20 11:30 UTC, rgrinberg requested changes
Can you disable this test by default? Writing an additional 20 megs every time we run the test seems a bit annoying.

2024-07-20 11:31 UTC, rgrinberg commented on test/blackbox-tests/test-cases/pkg/dune
> +  oneshot-webserver-large-file-curl-error))
This test depends on curl as well

2024-07-20 22:06 UTC, rgrinberg commented
Actually, the file size didn't need to be 20M to repro the problem. If it's 1M, then it should be enough to leave on by default.

2024-07-22 04:22 UTC, gridbugs commented
Ok I'll change it to 1M. On my machine I can't reproduce the problem with a 1M file, but github actions seem to be more sensitive to this issue than my machine is.

2024-07-29 01:52 UTC, gridbugs commented
This is no longer needed as the issue was fixed in https://github.com/ocaml/dune/pull/10753

2024-07-29 01:52 UTC, closed without merging