backport: Fix the compilation of OCaml 5 programs on Cygwin (#11009)
ocaml/dune pull request #11051
Opened 2024-10-29 11:16 UTC by maiste

This PR backports https://github.com/ocaml/dune/pull/11009. I have applied the change to both `Gcc` and `Clang` as the function has changed between `main` and `3.16`.

2024-10-29 15:33 UTC, kit-ty-kate commented on test/blackbox-tests/test-cases/cpp-std-ocaml5.t/cpp11.cpp
> +#include <cstring>
```suggestion
#include <iostream>
#include <cstring>
#include <caml/misc.h>
#include <caml/mlvalues.h>
```

2024-10-29 15:46 UTC, Leonidas-from-XIV requested changes

2024-10-29 15:46 UTC, Leonidas-from-XIV commented on src/ocaml/version.ml
> +let supports_hidden_includes version = version >= (5, 2, 0)
This seems questionable, I don't think it is part of the fix.

2024-10-29 15:46 UTC, Leonidas-from-XIV commented on src/ocaml/version.mli
> +val supports_hidden_includes : t -> bool
Same here.

2024-10-29 15:59 UTC, maiste reviewed
Let see if the tests succeed. If that's the case, I'll commit these changes.

2024-10-29 15:59 UTC, maiste commented on src/ocaml/version.ml
> +let supports_hidden_includes version = version >= (5, 2, 0)
```suggestion
```

2024-10-29 15:59 UTC, maiste commented on src/ocaml/version.mli
> +val supports_hidden_includes : t -> bool
```suggestion
```

2024-10-30 08:47 UTC, Leonidas-from-XIV approved these changes

2024-10-30 09:12 UTC, merged