Update promotion.rst to explain mode promote
ocaml/dune pull request #11122
Opened 2024-11-14 05:33 UTC by chris-armstrong

Explain the difference between diffing and promotion and the use of (mode promote)

2024-11-14 11:14 UTC, chris-armstrong commented
I've tried to fix the broken link, but not sure if that'll take

2024-11-19 14:37 UTC, Leonidas-from-XIV requested changes
Thanks for the changes! I've added a few notes on how to improve the wording and accuracy a little bit.

I've also ran CI and you can see that the link does in fact work: https://dune--11122.org.readthedocs.build/en/11122/concepts/promotion.html

2024-11-19 20:46 UTC, chris-armstrong commented
Thanks @Leonidas-from-XIV.  Please see my changes above, hopefully these adequetely address your comments.

2024-11-20 09:46 UTC, Leonidas-from-XIV reviewed
Thanks, I've added a few corrections but it's on the right way.

@christinerose can you please take a look at the text and check?

2024-11-20 09:46 UTC, Leonidas-from-XIV commented on doc/concepts/promotion.rst
> +(usually ``_build/<profile_name>``). You can use Diffing and Promotion flows
It's not a profile but context. I wouldn't go into specifics beyond `_build` really.

2024-11-20 09:46 UTC, Leonidas-from-XIV commented on doc/concepts/promotion.rst
> +copy their output into your source tree. This is more suitable for code or
More suitable than what?

2024-11-20 13:59 UTC, christinerose commented on doc/concepts/promotion.rst
> +the output of the rule with a copy in your source tree. It is useful when
```suggestion
its output with a copy in your source tree. It is useful when
```
Would this work to take out this one prepositional phrase? Reads a little smoother?

2024-11-20 14:15 UTC, christinerose commented on doc/concepts/promotion.rst
> +packaging in opam.
This last sentence is a little awkward. Does this say the same thing?

This approach suits code or documentation generation workflows where output needs to be checked to enable easier browsing or to eliminate dependencies on the code generation step during opam packaging.

If not, let’s work on it to clarify.

2024-11-20 14:16 UTC, christinerose commented
> Thanks, I've added a few corrections but it's on the right way.
> 
> @christinerose can you please take a look at the text and check?

I made a few minor grammatical changes and suggested a couple of sentence alteration for readability. See what you think!

2025-01-27 11:21 UTC, maiste commented
@chris-armstrong I have rebased the PR. Could you address the remaining comments? I think this PR is almost ready to be merged.

2025-01-27 23:48 UTC, chris-armstrong commented
Could you please take another look @maiste, hopefully this is ready to go

2025-01-28 08:55 UTC, maiste approved these changes
Thanks for your reactivity! Two small suggestions, but otherwise it looks good to me :+1: 
@Leonidas-from-XIV could you take another look at it when you have time to?

2025-01-28 08:55 UTC, maiste commented on doc/concepts/promotion.rst
> +=====================
```suggestion
```
Does not seem to be the case on the other files. Rst is supposed to take the top level title as the page title.

2025-01-28 08:55 UTC, maiste commented on doc/concepts/promotion.rst
> +copy their output into your source tree. This approach suits code
```suggestion
copy their output into your source tree. This approach suits, for example, code
```

2025-01-29 10:43 UTC, Leonidas-from-XIV approved these changes
Looks good but is failing the DCO check. @chris-armstrong can you sign off your commits?

2025-01-29 11:09 UTC, chris-armstrong commented
I don't know how to do what you're asking. 

Can we just close this PR - this was meant to be a small improvement to the documentation to make it clearer, but it's been back and forth several times over a few months that it seems hardly worth bothering with now.

2025-01-29 11:09 UTC, chris-armstrong commented
I'm happy to waive copyright on the changes in this PR if it makes it easier

2025-01-29 12:18 UTC, Leonidas-from-XIV commented
When accepting contributions we require the contributors to sign off that they possess the right to contribute the code etc. [See more about it here](https://dev.to/janderssonse/git-signoff-and-signing-like-a-champ-41f3).

This is achieved via the

In your case the easiest way via the `Signed-off-by: Your Name <you@example.com>` line in the git commit message, like [in my commit](https://github.com/ocaml/dune/pull/11122/commits/90185d7f395b49510ece5402373458f070eb1382).

The easiest way to add a signature to existing commits is to

```sh
$ git rebase main --signoff
$ git push --force
```

(This is also what I do when I forget to sign off my commits)

2025-01-30 09:37 UTC, merged

2025-01-30 10:05 UTC, maiste commented
Thanks @chris-armstrong for the contribution! :pray: