test: exhibit a bug when promoting directories
ocaml/dune pull request #11213
Opened 2024-12-16 12:12 UTC by panglesd

This shows a reproduction for the bug I'm about to open an issue about!

2025-01-10 15:02 UTC, Leonidas-from-XIV commented on test/blackbox-tests/test-cases/promote/deep-subdir.t/run.t
> +Tests for promoting directory targets
Generally we try to avoid cram test folders with multiple files. Can you rename this file into `deep-subdir.t` and inline the `dune` and `dune-project`?

Otherwise the test looks good to me!

2025-01-16 10:10 UTC, panglesd commented on test/blackbox-tests/test-cases/promote/deep-subdir.t/run.t
> +Tests for promoting directory targets
Thanks! And sorry for the delay: I missed the notification...

I now see that @ElectreAAS has [incorporated](https://github.com/ocaml/dune/pull/11226/commits/ea5bbbf1de50a0054a7150643fada86f158bd482) this PR into #11226, with your suggestion and along with a fix (thanks a lot!). Should I close this one then?

2025-01-16 12:56 UTC, ElectreAAS commented on test/blackbox-tests/test-cases/promote/deep-subdir.t/run.t
> +Tests for promoting directory targets
As you want, I incorporated your test because I wanted to be sure I wasn't making any existing bug worse, but that doesn't mean you have to close this PR
If you can apply Marek's suggestion we can merge this and I'll modify #11226 accordingly

2025-01-16 15:37 UTC, panglesd commented on test/blackbox-tests/test-cases/promote/deep-subdir.t/run.t
> +Tests for promoting directory targets
Done. (And signed the commits.)

2025-01-16 15:42 UTC, Leonidas-from-XIV requested changes
The tests needs to be made reproducible but otherwise looks good :-)

2025-01-16 15:42 UTC, Leonidas-from-XIV commented on test/blackbox-tests/test-cases/promote/deep-subdir.t
> +  Shared cache location: /home/panglesd/.cache/dune/db
Would the non `--verbose` run be enough? Otherwise you need to figure out paths and things that might change.

2025-01-27 10:46 UTC, panglesd commented on test/blackbox-tests/test-cases/promote/deep-subdir.t
> +  Shared cache location: /home/panglesd/.cache/dune/db
Sure! Sorry for the delayed answer...

2025-01-27 12:11 UTC, ElectreAAS approved these changes
Locally rebased, tested, and approved. Will merge once the CI is green.

2025-01-27 13:28 UTC, merged