Control+C handling
ocaml/dune pull request #1912
Opened 2019-03-06 15:44 UTC by aalekseyev

This PR deals with problematic behavior of dune when it's interrupted with Ctrl+C while running a build in polling mode.
Before this PR, dune would just fail with "assert false" and keep watching, among other weird behaviors.

After this PR, killing with Ctrl+C should just terminate dune quickly.

2019-03-06 18:45 UTC, aalekseyev commented
@diml, this should be ready for review now. The first two commits implement the actual fix, and the rest are a cleanup with no significant intended change of behavior.

2019-03-07 08:05 UTC, ghost requested changes

2019-03-07 08:05 UTC, diml commented on src/scheduler.ml
> +    | Error exn -> (exn, Some (Printexc.get_raw_backtrace ()))
We should probably capture this backtrace earlier, i.e. when constructing the original `Error exn`

2019-03-07 08:05 UTC, diml commented on src/scheduler.ml
>  let go_rec t =
We can probably get rid of this layer

2019-03-07 08:09 UTC, diml commented
Thanks, the result does look easier to follow. BTW, looking again at this file, the function names are not great: we have `go_rec` that is called by `run`, itself called by `run_and_cleanup` which is then called by both `go` and `poll`. I suggest to put the first three functions into a sub-module `Run_once` or `Main_loop` that only exposes `run_and_cleanup` and maybe rename `go_rec` to something else, such as `main_loop`.

2019-03-07 10:37 UTC, aalekseyev commented
Pushed the changes.
I renamed `go_rec` to `pump_events` because that seems like what it's doing.

2019-03-07 10:54 UTC, ghost approved these changes

2019-03-07 10:54 UTC, diml commented on src/scheduler.ml
> +          Fiber.return (Got_signal : pump_events_result)
We should be able to get rid of this type annotation now:

```suggestion
          Fiber.return Got_signal
```

2019-03-07 11:46 UTC, merged