If a dune file uses OCaml syntax, use ocamlformat
ocaml/dune pull request #2014
Opened 2019-04-03 12:39 UTC by emillon

Closes #2012

I'm not sure what causes the difference in order.

Notes on this patch:
- this reads dune files during rule generation. This might be a problem. Alternatively, it might be possible to do that in the build action.
- enabling/disabling is defined by the formatter used, not on the file name. That is, `(only dune)` will not format dune files in ocaml syntax.

2019-04-03 12:54 UTC, rgrinberg approved these changes

2019-04-04 12:49 UTC, ghost requested changes

2019-04-04 12:49 UTC, diml commented on src/format_rules.ml
> +          match Format_dune_lang.parse_file (Some file) with
Parsing the whole file again feels a bit much. We just need to use `Dune_lexer.is_script` which only inspects the first line.

2019-04-04 12:50 UTC, diml commented
BTW, I suggest to simply make `dune format-dune-files` ignore dune files in OCaml syntax. It's less work for the main `dune` doing the build and in practice dune files in OCaml syntax are not really recommended.

2019-04-05 04:59 UTC, rgrinberg commented
Btw, once we have generic actions, `dune format-dune-file` can be eliminated. We can just use a generic action to set up the formatting rules.

2019-04-09 11:26 UTC, emillon commented
OK I'll make the formatting rules ignore ocaml syntax. Seems simpler indeed!

2019-04-09 11:51 UTC, emillon commented
Done!

2019-04-09 12:49 UTC, merged