[WIP] running inline tests with javascript/nodejs
ocaml/dune pull request #2266
Opened 2019-06-11 04:33 UTC by hhugo

I'd like to run inline_tests (including expect tests) with JavaScript.

I was able to have something running with this PoC and https://github.com/ocsigen/js_of_ocaml/pull/817 ```
```
dune build @lib/tests/javascript-runtests
```

One of the constraint is that inline_tests that link with js_of_ocaml (the lib) can only be used in a JavaScript context. Ideally, I'd like to be able to specify that some tests run in JavaScript only, native only or both.

Do you have any suggestion on how to achieve that   ?

2019-06-12 10:13 UTC, diml commented
Running inline tests in JavaScript seems good, thanks for looking at this!

Regarding how to specify which contexts to run the tests in, I suppose we could add a field `modes` to the `inline_tests` field. Then one could write `(library ... (inline_tests ... (modes js byte native)))`. The default would be `(modes best)`.

2019-06-12 14:56 UTC, hhugo commented
Thanks. I've implemented your proposal. I'll try to write some tests later.

2019-06-13 09:16 UTC, ghost requested changes

2019-06-13 09:16 UTC, diml commented on src/inline_tests.ml
> +               match Bin.which ~path:((Super_context.context sctx).path) runner with
We should use `Super_context.resolve_program` here

2019-06-15 04:05 UTC, hhugo commented
I've updated the PR with tests

2019-06-17 11:01 UTC, diml commented
Thanks. I moved the tests to js_of_ocaml since they need nodejs to run (these are run as part of a separate `runtest-js` alias) and added some doc.

2019-06-17 11:07 UTC, merged