dune subst reads from dune-project
ocaml/dune pull request #2955
Opened 2019-12-05 22:10 UTC by fangyi-zhou

Signed-off-by: Fangyi Zhou <me@fangyi.io>

Working in progress for #2910

2019-12-05 22:11 UTC, fangyi-zhou commented
Well, I meant to create a draft pull-request but misclicked

2019-12-10 08:57 UTC, ghost requested changes

2019-12-10 08:57 UTC, diml commented on src/dune/watermarks.ml
> +  let files_ = String.Set.of_list (List.map ~f:Path.to_string files) in
`files_` is not super explicit as a variable name, I propose to call it just `files` and move it under `let dune_project`, i.e.:

```ocaml
  let dune_project =
    let files = ... in
```

2019-12-10 08:57 UTC, diml commented on src/dune/watermarks.ml
> +module Dune_project_mini = struct
Initially, the intent of this sub-module was to not do a complete decoding of the `dune-project` file and keep enough information to edit it. However, now that we are fully loading the `dune-project` file it makes less sense to also load it again in a minimal way on the side. At this point we are only relying on this module for editing the `dune-project` file, so I propose to rename it `Dune_project_editor` instead, to state its purpose more clearly.

We could also extend the main `Dune_project` module to keep the necessary information to do the edition. It's not a requirement for this PR, but you are welcome to have a look if you feel motivated :)

2019-12-10 08:57 UTC, diml commented on src/dune/watermarks.ml
> +let make_watermark_map_dune_project ~commit ~version ~dune_project =
Just to keep the code as obvious as possible, I propose to rename the original function `make_watermap_map_from_opam_file` and this function `make_watermap_map_from_dune_project`

2019-12-10 09:00 UTC, diml commented
No worries for the draft status. I left a couple of comments but otherwise it looks good to me!

Could you also add a test for this please? To do so, you need to add a directory with a `run.t` file in `test/blackbox-tests/test-cases`. Then run `dune runtest --auto-promote` once to update the boilerplate and then `dune runtest` or `dune build @name-of-your-test` to run the test. The format of tests is [cram](https://bitheap.org/cram/), i.e. lines starting with `  $` are commands to run and lines starting with two spaces are the expected output of the commands. You can use `dune runtest` followed by `dune promote` to automatically update the `run.t` file with the actual output of commands.

2019-12-10 21:45 UTC, fangyi-zhou commented
Still working in progress.

I don't see any way to modify the dune project by the exported API, so I guess we'll have to leave the editor here for the moment being. I changed the editor module to extend the original `Dune_project` module.

With regards to testing, I see we're having a problem. Now `dune-project` files takes precedence over `.opam` files, so some substitution tests are failing due to non-backward compatible behaviour. Should it be the case, or we should first check for `.opam` file, then look for `dune-project` file to preserve some backward compatibility?

2019-12-11 12:20 UTC, diml commented
I added `[WIP]` in the title to make it clear that it is still in progress, you can remove it when you consider it ready.

> I don't see any way to modify the dune project by the exported API, so I guess we'll have to leave the editor here for the moment being. I changed the editor module to extend the original Dune_project module.

Seems good to me. The current code looks clear.

> With regards to testing, I see we're having a problem. Now dune-project files takes precedence over .opam files, so some substitution tests are failing due to non-backward compatible behaviour. Should it be the case, or we should first check for .opam file, then look for dune-project file to preserve some backward compatibility?

Hmm, that's odd. I'm looking at the failing tests and I would have expected the information to be capture by the `Package.t` value in the `Dune_project.t` one, and so for the variable to still be substituted.

2019-12-11 14:05 UTC, diml commented
Ah ok, I just remembered that we don't parse all the fields when reading opam files in `Dune_project`. The code is at the end of `dune_project.ml`, in the load function. After reading the opam file, we generate a `Package.t` record where most fields are set to dummy values. We only read the version.

One possibility is to change this code to instead read the data from the opam file. We can use the code in `make_watermark_from_opam_file` for that. We can then extract it into a function that turns an opam file into a `Package.t` and use this function in `make_watermarl_from_opam_file`, so that we use the same code path whether we have a `dune-project` file or not.

2020-01-15 15:57 UTC, diml commented
@fangyi-zhou did you have a chance to take another look at this issue since last time?

2020-01-15 18:10 UTC, fangyi-zhou commented
I'll try to work on it a bit tonight, otherwise I'm fine if someone would like to take over from me, or start a new PR

2020-01-16 09:55 UTC, diml commented
Ok, let me know how it goes. Happy to help finishing the PR.

2020-01-16 11:30 UTC, fangyi-zhou commented
@diml In my last commit, I load the opam package and superpose it with dune-project, but the test is still failing as follows:

```
   $ git tag -a 1.0 -m 1.0
 
   $ dune subst
+  File "file.ml", line 2, characters 15-30:
+  2 | let authors = "%%PKG_AUTHORS%%"
+                     ^^^^^^^^^^^^^^^
+  Error: variable "authors" not found in dune-project file
+  Loaded foo
+  [1]
 
   $ cat file.ml
-  let name = "foo"
-  let authors = "John Doe <john@doe.com>"
-  let version = "1.0"
+  let name = "%%NAME%%"
+  let authors = "%%PKG_AUTHORS%%"
+  let version = "%%VERSION%%"
```

Your help is much appreciated

2020-01-16 16:09 UTC, diml commented
Superposing the two sources of information is not ideal. Dune makes sure there is only one source of information written by the user: the opam files or the dune-project file. But we can't have both. I'm refactoring a bit the code to make that more explicit.

2020-01-16 16:47 UTC, diml commented
I reworked a bit the code. Now all the information is collected and merged right from the start and contained in `Dune_info.packages ...` and there is only one way to create a watermark map in `watermarks.ml`.

Merging this now. Thanks for you contribution to Dune!

2020-01-16 16:47 UTC, merged

2020-01-16 16:48 UTC, fangyi-zhou commented
Thanks a lot for the help!