Fix typos
ocaml/dune pull request #4119
Opened 2021-01-14 16:34 UTC by MisterDA

A new round of typo fixes :)
I noticed some errors were introduced in the doc with the latest 2.8 merges, so I fixed them and also ran a checker on the code.

2021-01-14 17:02 UTC, voodoos approved these changes
Good idea !

2021-01-14 17:08 UTC, voodoos requested changes
Good idea, but you need to reformat the code !

2021-01-14 21:08 UTC, voodoos approved these changes

2021-01-15 11:15 UTC, emillon commented
Thanks!

2021-01-15 11:15 UTC, merged