Teach dune make's jobserver API
ocaml/dune pull request #4331
Opened 2021-03-09 00:28 UTC by rgrinberg

Since this is technically a breaking change, I thought we might as well do it in 3.0

I went for a very simple implementation that reuses the background thread task queue from csexp_rpc. There's probably  a better way to do this however.

2021-03-09 21:12 UTC, rgrinberg commented
> Great! Just to be clear it is adding dune as a user of the API (e.g. dune is a sub-process of make), not the other way.

Yeah, although it would be nice if dune was a server as well.

> For the other way around, i.e. dune sharing parallelism with commands it starts, there is one pitfall: if the command crashes without releasing its token then the tokens are lost forever and parallelism is reduced for the rest of the build.

Not necessarily. When the process that dune launched terminates, we can always release any unreleased tokens.

> That's something to be careful for this PR as well: does Dune make sure to always release its tokens when it is a client?

Yeah, that's a good point. Let me double check.

2021-03-10 12:36 UTC, jeremiedimino commented
> Not necessarily. When the process that dune launched terminates, we can always release any unreleased tokens.

But how do you do that?

2021-03-10 12:40 UTC, jeremiedimino commented
FTR, we stumbled upon this while implementing the protocol in jenga, and AFAIK it is not possible to recover the lost token as the protocol doesn't tell you who is holding them. We looked this up and found out that they hit the same problem in rust, but didn't find a solution.

It seems to be a problem with the protocol itself. So for this reason I'm a bit nervous to expose this to command run by dune directly. At the same time, it would be nice to share parallelism when you call `make` to build some foreign project. So maybe we could allow it but make it a per-rule explicit opt-in.

2021-03-10 14:26 UTC, jeremiedimino commented
> Proposition by-stanza: Dune could create a jobserver by action (optionaly with opt-in), it is not optimal but it could be sufficient for this use case. When dune has enough task to run itself it doesn't give a token to the jobserver, when it is waiting for this task it adds token to the jobserver of the task. When the task fails or finishes Dune knows that it got back all the tokens whatever if they have been really given back to the job server.

But what if you have several such actions running in parallel? Ideally you want to give tokens to the action that wants more token, but there is no way of knowing that.

What I had in mind was something more lightweight: we add an opt-in and document the fact that such actions have to be careful of always giving back their tokens. We can assume that make is safe, given that this protocol was designed for recursive invocations of make.

2021-03-10 15:02 UTC, rgrinberg commented
> FTR, we stumbled upon this while implementing the protocol in jenga, and AFAIK it is not possible to recover the lost token as the protocol doesn't tell you who is holding them. We looked this up and found out that they hit the same problem in rust, but didn't find a solution.

I see. So the issue is that whenever a token is read from the fifo, we don't know who the reader is. 

I wonder if we should just tweak the protocol to fix this issue, and use this new protocol to communicate with opam. Dune could still respect make's protocol, but would prefer its own when available. The main goal for me with this feature is to have  something that works with `opam install` and OPAMJOBS, and they don't yet have a jobserver implementation yet anyway.

2021-03-10 15:15 UTC, jeremiedimino requested changes

2021-03-10 15:15 UTC, jeremiedimino commented on src/dune_engine/scheduler.ml
> +          Task_queue.task write ~f:(fun () -> Jobserver.Job.release job)
We don't need to wait for the token to be written here. We should just queue it, signal the writer thread and move on.

2021-03-10 15:15 UTC, jeremiedimino commented on src/jobserver/jobserver.mli
> +open Stdune
doc please

2021-03-10 15:15 UTC, jeremiedimino commented on src/jobserver/jobserver.mli
> +open Stdune
There should be a url pointing to the jobserver spec

2021-03-10 15:15 UTC, jeremiedimino commented on src/dune_engine/scheduler.ml
> +    | Jobserver of Fiber.fill
`Rpc` and `Jobserver` seems to be exactly the same. What about replacing them both by a single `Thread_safe_ivar` event?

2021-03-10 15:23 UTC, jeremiedimino commented
That seems overkill if you ask me. Like trying to somehow wrap an unsafe protocol into an safe one. I think we should just use the protocol the way it was intended to be used and accept that it relies on command doing the right thing.

Now, there is another problem that requires some discussion: when a client starts, it always holds at least one token. Let's say this client wants to do X1 and X2 in parallel. For X1, it will simply reuse its current token. And before starting X1, it will spawn a separate thread that will wait for a token and do X2.

Now let's say that X1 finishes before X2 has had a chance to get its token. What do you do?

- option 1: you send the token back to X1, which means that for some time you might have 0 token. This seems pretty strange, and might lead to a situation where there parent ends up spawning an unbounded number of processes with 0 token
- option 2: you cancel X2 waiting for its token, and run X2 in the current thread

Option 2 is what we did inside Jane Street. However, it requires being able to reliably cancel a system call. Which is pretty tedious. @aalekseyev wrote a small library for it, we reproduce it in Dune.

But I'm curious what other implementations are doing. From what I know, rust implemented the jobserver protocol, might be worth checking. If everyone is going for option 1, perhaps with some mitigation, I feel like we should do the same to make our lives easier. Plus if they do that, whether dune does it or not won't make a big difference in the end.

2021-03-10 15:26 UTC, jeremiedimino commented
> I wonder if we should just tweak the protocol to fix this issue, and use this new protocol to communicate with opam. Dune could still respect make's protocol, but would prefer its own when available. The main goal for me with this feature is to have something that works with opam install and OPAMJOBS, and they don't yet have a jobserver implementation yet anyway.

Ah, well there is also the idea of having opam setup a single workspace and run dune only once, which would lead to even faster build times.

2021-03-10 15:27 UTC, jeremiedimino commented
Using `select` reliably requires setting the fd in non-blocking mode, which the protocol forbids.

2021-03-10 15:40 UTC, jeremiedimino commented
My overall thoughts on the jobserver are:

- if it's just for opam and dune, we can do something better and simpler
- we should either accept the jobserver protocol as it is with its limitations or not accept it at all. Even if we make the Dune implementation super robust, there are always many participants in a jobserver and we don't know what they do. So we'll only get weak guarantees at the cost of complex code to maintain
- if we want a general and better protocol, we should design a robust protocol, and then present it and discuss it with other build systems, to see if we can get something better adopted by the build system community

2021-03-10 15:56 UTC, jeremiedimino commented
It's said there: https://www.gnu.org/software/make/manual/html_node/POSIX-Jobserver.html

If you put it in non-blocking mode, it's going to be put in non-blocking mode for everyone and some clients might not expect that.

2021-03-10 19:25 UTC, aalekseyev commented
I guess implementation trumps the docs. I have to admit I never looked at the implementation, actually. Indeed the cancellation is much simpler if we demand that the fd is nonblocking.

2021-03-11 08:56 UTC, jeremiedimino commented
Alright then, the jobserver comes from GNU Make, so let's treat GNU Make as the reference implementation. That means that we have the full story for this PR then, which is about making Dune a jobserver client. It'd be nice to send an email to the GNU Make devs though. Maybe they are not aware the doc is not in line with the code. @bobot, ccccccnirndo you want to send this email? Happy to do it otherwise.

BTW, I was thinking again about the loss of tokens issue, and it occurred to me that we can always turn a loss of tokens into a temporary loss of tokens by re-creating the jobserver in between builds in polling mode. This means that the build will temporarily be slower in some cases, but on the other hand we keep a simple design.

2021-03-16 10:42 UTC, jeremiedimino commented
I haven't got a response from the GNU make developers yet, but I skimmed through the [mails related to the jobservers](https://lists.gnu.org/archive/cgi-bin/namazu.cgi?query=jobserver&submit=Search%21&idxname=bug-make&max=20&result=normal&sort=date%3Alate) and TBH that doesn't make me very confident in using pipes for sharing parallelism:

- putting the reading side in non-blocking mode is a recent change (GNU Make 4.3) and has [caused pain for users](https://lists.gnu.org/archive/html/bug-make/2021-01/msg00010.html). There are several threads talking about blocking/non-blocking
- I found [this mail](https://lists.gnu.org/archive/html/bug-make/2021-02/msg00005.html) where one of the maintainer reflects on using pipes for sharing parallelism

My overall impression is that using pipes for this was a nice idea, but it has many issues in practice and might not be worth the troubles. @rgrinberg I know that you care about this for `opam install`. @bobot do you have a particular interest in the jobserver for Frama-C?

2021-03-16 11:17 UTC, jeremiedimino commented
That could work.

Another idea would be to make Dune understand the Makefile language. A bit ambitious, but I'd be keen to try that during a Dune retreat :)

2021-07-25 14:26 UTC, dra27 commented
This passed me by (I blame UK lockdown 3, though I blame it for most things!). Is this still hoped for Dune 3.0? Two reasons for asking - the Windows implementation of jobserver is _really_ easy (it's just a named semaphore - in fact, it's not immediately clear to me why they don't allow that for the POSIX jobserver as well, but perhaps GNU make still runs on a lot of very non-POSIX-y platforms).

More importantly, I did a bit of hacking on the train this weekend with opam and prototyped jobserver support for opam (it's working correctly with two `make`-based test packages - I didn't try this version of Dune). I don't think it would be too hard to add the support to opam (possibly requiring `["dune" "build" "@install"] {jobserver}` or maybe just enabled by default), and that would mean that opam installing multiple Dune packages would also stop blowing the jobcount...

2021-08-16 09:42 UTC, aalekseyev commented
Speaking of fun edge cases, we saw a case where Linux in some cases decides that [write] should block even though there's very little data in the internal buffer of the pipe (even 1 byte can be enough).

This breaks the jobserver model (makes it deadlock). You can work around this by reading from the pipe periodically and writing again. I wonder how make deals with that.

2021-12-02 18:34 UTC, SkySkimmer commented
This PR fixes https://github.com/ocaml/dune/issues/2647 btw

2021-12-02 18:52 UTC, jeremiedimino commented
At this point I have seen so many problems with this protocol that we wouldn't be doing anyone a favour by implementing it. Dune or commands spawned by Dune would just start freezing in many situations and it would be a pain to debug. Dune would just become a less reliable software. Let's stop there.

2021-12-02 18:52 UTC, closed without merging

2022-02-23 16:33 UTC, JasonGross commented
Does dune expose it's jobserver in some way, so that I could write an external shim that interfaces between dune's job server and make's job server?

2022-02-24 16:33 UTC, rgrinberg commented
@JasonGross how do you plan to workaround the issues pointed by Jeremie if you implement the protocol?

2022-02-24 18:14 UTC, JasonGross commented
@rgrinberg I'm interested in a best-effort approach that doesn't tie dune to the limitations of make's jobserver protocol, but instead has a separate process that interops between the jobservers of dune and make.  My use-cases are:
- [Building Coq via make hangs my machine unless I pass single-threaded flags to make and dune separately](https://github.com/coq/coq/issues/15730)
- [Coq's internal parallelism cannot be shared with dune nor with make](https://github.com/coq/coq/issues/14203)

My primary desideratum is that if the overall build would succeed (given enough cores and memory) when the parallelism modes uncoupled, then the shim should not cause the build to fail / hang / deadlock.

The most important issue to me seems to be:

> Speaking of fun edge cases, we saw a case where Linux in some cases decides that [write] should block even though there's very little data in the internal buffer of the pipe (even 1 byte can be enough).
> 
> This breaks the jobserver model (makes it deadlock). You can work around this by reading from the pipe periodically and writing again. I wonder how make deals with that.

This is easy to fix: the shim interoping between make's jobserver and dune's should have a dedicated thread for writing to the pipe on the make-side, and interaction on the dune-side should not block on this thread.

2022-02-24 18:15 UTC, ejgallego commented
@JasonGross note that for both of your use cases, alternative solutions are planned. In the first case, we will eliminate make completely, in the second, documents managers should take care of that, and it is beyond what dune can do.