Fix many different issues of Sites
ocaml/dune pull request #4645
Opened 2021-05-21 22:06 UTC by bobot

Should fix:
 - #4219 by adding an underscore for site name that start with an OCaml keyword and finish with underscores
 - #4325 by adding location in `Section_with _site`
 - #4212  and #4198 by:
    - not promoting the install file during `dune build -p <pkg> @install`
    - creating the install file during a new phase `dune install -p <pkg> --create-install-files <pkg>` which substitute the files if needed into an intermediate directory
 - #4415 by delaying the computation of the content of the generated file

2021-05-26 21:54 UTC, rgrinberg commented on src/dune_rules/artifact_substitution.ml
> +  let ic = Io.open_in src in
This should be lazy IMO. It's cleaner to have all the side effects inside fiber.

2021-05-26 21:57 UTC, rgrinberg commented on bin/install_uninstall.ml
> +    and+ create_install_files =
If it's not actually installing, why does it need to be under the `install` subcommand? Can't this be done just by building a target.

2021-05-26 21:58 UTC, rgrinberg requested changes

2021-05-26 21:58 UTC, rgrinberg commented on src/dune_rules/artifact_substitution.ml
> +let test ~input =
This function is too similar to `copy`.  The common code should be factored out.

2021-05-27 17:33 UTC, rgrinberg commented on src/dune_rules/artifact_substitution.ml
> +  let ic = Io.open_in src in
Consider this:

```ocaml
let test_src = test_file ~src () in
let* test_src = test_src ..
```
You're opening the channel after the first `let`, but clean up is reserved until the bind.

I would prefer if all the side effects occur after the bind.

2021-06-03 15:15 UTC, ejgallego commented
@rgrinberg , would you mind re-reviewing this?

Ideally we should get it merged soon as to have it in 2.9

2021-06-04 00:37 UTC, rgrinberg approved these changes

2021-06-07 19:42 UTC, ejgallego commented
@bobot , 2.9 ping

2021-06-09 14:55 UTC, merged

2021-06-10 20:40 UTC, ejgallego commented
@bobot , sorry for not looking at this closely before, but it seems to me that this PR landed in 2.9 but not in `main`, is that intended?

Note that:
- there are no changes entry in this PR
- the bugs you mention in the PR summary have not been closed due to the target branch