[RPC] improve connection handling
ocaml/dune pull request #4661
Opened 2021-05-27 19:33 UTC by rgrinberg

The previous code would wait for all waiting to initialize before
serving a single session. This would cause unnecessary delays if clients
would stall.

@cwong-ocaml I think this should fix the "delays" you've been
encountering

@jeremiedimino some advice on how to write this code cleanly would be
appreciated.

2021-05-27 21:57 UTC, rgrinberg commented
Adding @aalekseyev as a reviewer as he's aware of the issue.

2021-05-27 23:09 UTC, jeremiedimino commented
You could introduce some function to extract the stream merging logic.

However, this still doesn't solve the underlying issue: if there is a stale "pending client", the code that iterates over the pending clients is still going to get stuck and will never terminate cleanly. That should be less of an issue after this PR, but still doesn't feel completely right and could cause further issues in the future. For instance we end up wasting file descriptors.

Ideally, Dune we would be able to detect stale clients and ignore them. Or better, have a way for clients to be notified when the server starts without requiring the server to establish the connection.

2021-05-27 23:13 UTC, rgrinberg commented
> Ideally, Dune we would be able to detect stale clients and ignore them.

Isn't this just a bug in the client code? They should be removing the stale socket files.

> Or better, have a way for clients to be notified when the server starts without requiring the server to establish the connection.

Perhaps we could just have the server drop a file in _build/rpc to say that it's listening and the clients can poll for it? It's a bit wasteful, but so is the current code if the clients are being bad.

2021-05-27 23:26 UTC, jeremiedimino commented
> Isn't this just a bug in the client code? They should be removing the stale socket files.

This also happens if the client is killed -9.

> Perhaps we could just have the server drop a file in _build/rpc to say that it's listening and the clients can poll for it? It's a bit wasteful, but so is the current code if the clients are being bad.

That would work. In fact, doesn't the server already drop a file there? I'm thinking of the server listening socket.

2021-05-27 23:29 UTC, rgrinberg commented
> That would work. In fact, doesn't the server already drop a file there? I'm thinking of the server listening socket.

Yeah. Either the socket file for Unix or a little text file with the TCP address for Windows.

I will prepare a PR then.

By the way, one disadvantage is that the client will now observe a little more latency when running dune after the client is running. Note a huge deal in watch mode, but if we wanted dune to report errors in without `-w` as well (using the same mechanism), the latency would get annoying.

2021-05-27 23:45 UTC, jeremiedimino commented
I guess the latency could be improved by watching the file with inotify? (or equivalent)

2021-05-27 23:53 UTC, rgrinberg commented
As you know, inotify only exists on Linux. It wouldn't be realistic to write this code for every platform, and spawning a process like fsevents just for one watching one file is also not very appealing.

2021-05-28 00:52 UTC, rgrinberg commented
Actually, I'm wondering if we are too quick to abandon the current solution. To fix the issue you described we just need to handle errors from `Unix.connect` so that the waiting_clients fiber terminates on the server.

2021-06-01 09:24 UTC, jeremiedimino commented
Handling errors from `Unix.connect` might be a step further but we don't know yet if it is the full story.

The current design is not ready and we wasted enough time because of it so far. Having the client poll for the server is a simpler design. So let's switch to that for now. 

We can re-consider the server connection to sleeping clients once we have a more extensive test-suite for this design.

As a side-note, we shouldn't be paranoid about polling for now. Indeed, every single OCaml program that use threads gets a ticker thread and so will never truly go idle.

2021-06-01 20:37 UTC, rgrinberg commented
Alright, I pushed a commit that switches to polling.

2021-06-02 09:29 UTC, jeremiedimino commented on bin/rpc.ml
> +              raise Dune_util.Report_error.Already_reported)
If you raise here, you will never get `res = Error ()`, so the `Error () -> ()` branch bellow is dead code. Did you mean to raise here?

2021-06-02 09:32 UTC, jeremiedimino commented on src/dune_rpc_impl/run.ml
> +          Scheduler.Worker.task waiter ~f:(fun () -> Unix.sleepf 0.2)
Feels like the code could be simplified with a `task_exn` here.

2021-06-02 09:34 UTC, jeremiedimino requested changes
The new logic looks correct to me.

However, it seems to me that the `raise XXX.Already_reported` in `bin/rpc.ml` should be removed.

2021-06-02 15:47 UTC, jeremiedimino approved these changes
Looks good

2021-06-02 16:04 UTC, rgrinberg commented
@cwong-ocaml I got rid of --persistent and added --wait to simplify polling instead. The polling frequency is fixed to 5Hz, but I can make it customizable if you need to change it.

2021-06-02 16:26 UTC, cwong-ocaml commented
Thanks, will merge once CI passes so we can make the change.

2021-06-02 16:43 UTC, merged