Fix #5267
ocaml/dune pull request #5295
Opened 2021-12-14 04:54 UTC by rgrinberg

The idea is to represent all empty libraries the same way. This almost works but needs a workaround for odoc. Since it's an empty library, we shouldn't be generating a module index section.

2022-01-10 14:27 UTC, jeremiedimino requested changes

2022-01-10 14:27 UTC, jeremiedimino commented on test/blackbox-tests/test-cases/github3766.t/run.t
> +  ls: .../foo/*.a: No such file or directory
Seems like this test needs to be updated.

2022-01-10 14:27 UTC, jeremiedimino commented on test/blackbox-tests/test-cases/github759.t/run.t
> -  Foo
Is that expected?

2022-01-10 14:27 UTC, jeremiedimino commented on test/blackbox-tests/test-cases/merlin/src-dirs-of-deps.t/run.t
> -  Lib2
Is that expected?

2022-01-10 23:14 UTC, rgrinberg commented
Yes, that is the intent. Basically the idea is that the following should produce identical libraries:

```
(library (name x) (modules))
(library (name y) (modules) (wrapped false))
```

If the latter stanza doesn't produce have a toplevel entry point, then neither should the former. Wdyt of this rule?

2022-01-11 13:47 UTC, jeremiedimino commented
All wrapped libraries have a toplevel module so it seems to me that the ones with no module should have a toplevel module as well. Adding a special case for libraries with no modules feels like breaking continuity. `(wrapped false)` is not the standard way to declare libraries with Dune, so I wouldn't take it into account here.

In any case, I wouldn't go through such a change at such a late stage in the release cycle. It could delay the release more by introducing new breakages.

2022-01-21 01:59 UTC, rgrinberg commented
I'll think of a different fix but merge the test case.

2022-01-23 18:18 UTC, merged