fix: disable build path prefix map pre 3.0
ocaml/dune pull request #5448
Opened 2022-02-16 17:56 UTC by rgrinberg

This breaks existing ppx rewriters which rely on real paths existing in
build artifacts.

2022-02-16 17:57 UTC, rgrinberg commented
Fix this issue https://github.com/ocaml/opam-repository/pull/20721#issuecomment-1040863135

2022-02-16 20:13 UTC, snowleopard commented on test/blackbox-tests/test-cases/dune-cache/trim.t/run.t
> +  ./21/21da7f5efeb2d9ad464b4a413c98698b:((8:metadata)(5:files(8:target_a32:5637dd9730e430c7477f52d46de3909c)))
See the comment above about bumping `rule_digest_version`.

2022-02-16 20:14 UTC, snowleopard requested changes
The fix is very heavy-handed: every action is now going to store this silly `bool`, forever. Can we do something else instead?

2022-02-16 20:15 UTC, rgrinberg commented
I don't see any alternatives. Open to suggestions though.

2022-02-16 20:24 UTC, snowleopard commented
> I don't see any alternatives. Open to suggestions though.

Well, one alternative is to disable build prefix map globally, not per action. You can still bump `rule_digest_version` to ensure we aren't mixing up incompatible artifacts in the cache.

2022-02-16 20:26 UTC, rgrinberg commented
I should add that forever is a bit pessimistic. We can have a campaign to have this removed, but we need to inform users of this change and provide them with adequate workarounds. Given that none of that has happened, and there's really no time to do it for 3.0, I'm afraid we must support the old behavior somehow.

Also keep in mind that in the original PR we talked of potential issues and decided against versioning on the assumption that nobody relied on this. Well, this assumption turned out to be totally wrong.

2022-02-16 20:27 UTC, rgrinberg commented
> > I don't see any alternatives. Open to suggestions though.
> 
> 
> 
> Well, one alternative is to disable build prefix map globally, not per action. You can still bump `rule_digest_version` to ensure we aren't mixing up incompatible artifacts in the cache.

How would this work in workspaces with mixed 3.0 and 2.9 projects?

2022-02-16 20:35 UTC, snowleopard commented
> > > I don't see any alternatives. Open to suggestions though.
> > 
> > 
> > Well, one alternative is to disable build prefix map globally, not per action. You can still bump `rule_digest_version` to ensure we aren't mixing up incompatible artifacts in the cache.
> 
> How would this work in workspaces with mixed 3.0 and 2.9 projects?

I think we have `Execution_parameters` for this kind of thing, e.g. we add `Execution_parameters.action_stdout_on_success` to rule's digest. Presumably, execution parameters can also vary between projects in the same workspace.

2022-02-16 20:39 UTC, snowleopard commented
> I should add that forever is a bit pessimistic. We can have a campaign to have this removed, but we need to inform users of this change and provide them with adequate workarounds. Given that none of that has happened, and there's really no time to do it for 3.0, I'm afraid we must support the old behavior somehow.
> 
> Also keep in mind that in the original PR we talked of potential issues and decided against versioning on the assumption that nobody relied on this. Well, this assumption turned out to be totally wrong.

I agree that we should support the old behaviour. I just think we should try to find a more lightweight approach.

2022-02-16 21:09 UTC, rgrinberg commented
> 

Okay, let me try moving the flag into the Execution_parameters.

2022-02-17 03:32 UTC, rgrinberg commented
re-did things with execution parameters. It's indeed a lot cleaner now.

2022-02-17 12:17 UTC, snowleopard approved these changes
Great, much nicer indeed!

Just a minor nitpick: I think it's worth adding an explicit name for this property, like we do with `should_remove_write_permissions_on_generated_files` below, so that we don't need to duplicate the `> (3.0)` comparison.

```ocaml
let should_remove_write_permissions_on_generated_files t =
  t.dune_version >= (2, 4)
```

2022-02-17 15:53 UTC, merged

2022-02-17 16:57 UTC, snowleopard commented on src/dune_engine/build_system.ml
> +      , Execution_parameters.expand_aliases_in_sandbox execution_parameters )
@rgrinberg Something seems wrong: did you miss the build prefix property?

2022-02-17 17:01 UTC, rgrinberg commented
Yes, that's an embarrassing omission. Will send a fix.

Rudi.
On Feb 17, 2022, 9:57 AM -0700, Andrey Mokhov ***@***.***>, wrote:
> @snowleopard commented on this pull request.
> In src/dune_engine/build_system.ml:
> > @@ -388,7 +388,8 @@ end = struct
>       , can_go_in_shared_cache
>       , List.map locks ~f:Path.to_string
>       , Execution_parameters.action_stdout_on_success execution_parameters
> -      , Execution_parameters.action_stderr_on_success execution_parameters )
> +      , Execution_parameters.action_stderr_on_success execution_parameters
> +      , Execution_parameters.expand_aliases_in_sandbox execution_parameters )
> @rgrinberg Something seems wrong: did you miss the build prefix property?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>