Add a new line at the end of error reports
ocaml/dune pull request #6823
Opened 2023-01-04 10:43 UTC by esope

This is an attempt to fix issue #6158

2023-01-04 19:25 UTC, rgrinberg commented
Thanks for trying to address this. All the gratuitous newlines are a bit annoying. Can we print the `cut` only as a separator between errors?

@snowleopard what do you think of this change in principle? We can make it console backend dependent to avoid any inconvenience it might cause inside at jst for you.

2023-01-04 19:39 UTC, esope commented
I agree too that some of the added newlines are annoying, especially terminal ones.
I have not found how to implement the "add new lines only between messages" behavior: it seems there is no easy way to detect which message is the "last" one.
A different approach would be to add a new line _before_ a message. Maybe this would feel less annoying.

2023-01-04 19:40 UTC, rgrinberg commented
The behavior you describe sounds reasonable. In other words "Prepend a newline if we aren't the first message being printed".

2023-01-04 19:42 UTC, esope commented
OK, I will try with this approach when I find some free time, then.

2023-01-04 20:53 UTC, esope commented
This seems to bring much more reasonable results.
I am not sure that the use of a reference in a function that is passed to `Fiber.Mutex.with_lock` is correct. What is the best practice that you use in the dune codebase?
I will add a test as soon as possible.

2023-01-04 20:58 UTC, rgrinberg commented
It's correct. As long as it doesn't cross a bind, there's nothing to worry about.

However, why did you choose to put this change in build_system.ml? I would expect `Dune_util.Report_error.report` to be the place to do it.

2023-01-05 07:23 UTC, esope commented
OK, I moved the change to `Dune_util.Report_error.report`.

2023-01-05 16:28 UTC, snowleopard commented on src/dune_util/report_error.ml
> +    if !first_error then first_error := false
The reference never gets reset back to `true`, so I guess this feature doesn't interact well with file-watching builds. You'll need to add and use a mechanism for correctly handling rebuilds.

2023-01-05 16:29 UTC, snowleopard requested changes
I think we should either support file-watching builds, or disable this feature during file-watching builds, because the current implementation seems broken.

2023-01-05 16:30 UTC, rgrinberg commented
@snowleopard sounds good, but do you think we need a flag for this feature? Or are you happy changing the output internally as well.

2023-01-05 16:35 UTC, snowleopard commented
> @snowleopard sounds good, but do you think we need a flag for this feature? Or are you happy changing the output internally as well.

Yes, it seems nice to keep this feature behind a flag, at least for some time, since we are technically breaking Dune's public interface. For example, various tests calling out to Dune might break.

Internally, I think there is a high chance we would want to enable this feature.

2023-01-06 07:50 UTC, esope commented
Thanks for the feedback.
What should be the name of this flag? `--separate-error-messages`? Should this be controlled by an option in `dune-workspace` too?
In watch mode only, when this flag is on, what do you think about _always_ prepending the error message with a blank line?

2023-01-06 17:16 UTC, rgrinberg commented
1. That name sounds fine.
2. For now I wouldn't worry about this and we can even just add an environment variable to control this. If this setting is good in practice, we're just going to make it the default.
3. Why does this extra newline help in watch mode?

2023-01-07 13:23 UTC, esope commented
Thanks.
About point 3, this would remove the need of keeping an internal state (a `bool ref` in this case) when in watch mode. This means that there would be mo problem anymore related to memoization or rebuilds. Or am I mistaken?

2023-01-13 13:08 UTC, esope commented
OK, I added the flag `--separate-error-messages` to control the new behavior of `Dune_util.Report.report`.
The flag is always off when watch mode is enabled.

2023-01-16 04:43 UTC, snowleopard commented on bin/common.ml
> +               always disabled when watch mode is enabled.")
```suggestion
               currently disabled in the file-watching mode.")
```

2023-01-16 04:46 UTC, snowleopard commented on test/blackbox-tests/test-cases/error_messages_separated.t
> +the forst message, and no blank line is inserted after the last
```suggestion
the first message, and no blank line is inserted after the last
```

2023-01-16 04:49 UTC, snowleopard commented on bin/common.ml
> +        (* this flag is ALWAYS DISABLED when dune works in watch mode *)
```suggestion
        (* This flag is currently disabled in the file-watching mode. To be fixed. *)
```

2023-01-16 04:52 UTC, snowleopard reviewed
Thanks, looks good now! I left a couple of suggestions.

It shouldn't be hard to make this flag work for the file-watching mode, I think. Perhaps, `Memo.Run.t` can be stored alongside the `bool ref` to decide when that `ref` gets stale and needs to be reset.

2023-01-16 15:23 UTC, esope commented
Thanks for the feedback, @snowleopard . I implemented your suggested fixes.

2023-01-17 02:09 UTC, snowleopard reviewed
Thanks! I'll leave it to @rgrinberg to approve and merge. (As far as I'm concerned there are no blockers any more.)

2023-01-22 11:31 UTC, esope commented
@rgrinberg, I'm happy to integrate more changes, should you have any.

2023-01-22 15:40 UTC, rgrinberg commented
Tbh, I think we need to make sure this feature works with watch mode before we consider it for merging. Watch mode is the recommended way to use dune, and whatever feature we're adding should work with it out of the box.

2023-01-22 16:21 UTC, esope commented
Understood. I'll have a second look at it, then.

2023-01-22 16:43 UTC, Alizter commented
I was also going to mention that it might be a good idea to allow for a config option, so that users can enable this by default if they desire.

2023-01-22 17:45 UTC, esope commented
OK, I've pushed some modification to support file-watching mode.
When file-watching mode is disabled, the behavior is the same as before (a blank line is inserted between error messages).
When file-watching mode is enabled, then a blank line is always printed _after_ each error message. This makes the implementation correct wrt caching, and I think this gives a consistent experience to users.

I'll wait for your feedback before dealing with config option issue.

2023-01-25 14:11 UTC, Alizter commented on src/dune_util/report_error.ml
> +(* Type for the [separate_error_messages_flag] value *)
Make the comments in this file `(**`

2023-01-25 14:13 UTC, Alizter approved these changes

2023-01-25 16:21 UTC, esope commented on src/dune_util/report_error.ml
> +(* Type for the [separate_error_messages_flag] value *)
Done in the last commit.

2023-01-28 04:41 UTC, rgrinberg commented
@gasche what do you think about the behavior proposed for watch mode? It seems alright to me.

2023-01-28 06:09 UTC, gasche commented
Thoughts (but: remember that I know very little about dune internals):

1. The observed behavior looks nice to me, and the compromise of having a different behavior when watching or not seems reasonable.
2. I wonder how the compiler should deal with the same feature requirement. In particular I wondered if there was a solution in the compiler that is satisfying and would require no change to dune. (Then we should do it this way rather than changing dune.) But unfortunately I don't see it. We could take inspiration of the logic here and print a line before each message that is not the first, and I *think* that the two logics would compose nicely. (Or we could add a blank line after each message, and then dune should not do anything, but we have the same problem as in @esope's first attempt that it's not so nice.)
3. Looking at the implementation, I wonder why the change is at the "report error" level rather than the `Console.print_user_message` level. It looks like the Console level (1) sees more messages that may also benefit from newline separation, and (2) may have precise knowledge of when the console is cleared, and the ability to accurately maintain state on whether we are the first message or not.

In any case, thanks everyone for looking at this. It's a small thing, but I think it could make a positive difference especially for beginner OCaml users.

2023-02-08 14:42 UTC, emillon commented
@esope do you think you'll be able to fix this this week? otherwise I'm happy to move this back to 3.8 (at the moment the 3.7 release is blocked on this feature). Thanks!

2023-02-09 18:13 UTC, esope commented
I can find some time next week. Sorry I've been pretty busy and unresponsive lately.
It is ok for me to leave this to 3.8.

2023-02-10 18:40 UTC, esope commented
I moved the logic for adding blank lines to `Dune_console.print_user_message` as suggested by @gasche .
This should cover more cases than before. I see no difference in practice with the previous version.

I have not tried to have different behaviors for the different console backends, because I don't see what could be specifically done for a particular backend, and because this would necessitate to duplicate code into the different backends, I think.
You guys might have different opinions, though.

2023-02-10 20:52 UTC, gasche commented
Two comments from an outsider:
- Nitpick: the name `error` is less appropriate at this abstraction level, maybe `separate_error_messages => separate_messages` and `first_error` => `first_message`?
- Logic: maybe you could set `first_message := true` in the `reset` and `reset_flush_history` functions, and this code would magically work for the watch mode as well? (I'm assuming the watch mode is implemented by calling `reset` to clear the terminal). Then you could simplify your code quite a bit.

2023-02-11 12:39 UTC, snowleopard commented
I quite like both of @gasche's suggestions!

2023-02-11 14:23 UTC, esope commented
Very good remarks, indeed! Thanks!
Both are now implemented.

2023-02-16 21:10 UTC, esope commented
I can hear no more requests for changes, does this mean everybody is happy about this implementation?
If this is a yes, this should probably be merged.

I will be happy to add an environment variable or an option in `dune-project` in a subsequent PR to control this setting more easily, if you think this is useful.

2023-02-19 18:17 UTC, esope commented
@snowleopard I updated the (now quite old) changes you requested, as well as @gasche 's.
I would very much like, that we make progress on this issue.

2023-02-21 03:39 UTC, snowleopard commented on CHANGES.md
> +- Allow running `$ dune exec` in watch mode (with the `-w` flag). In wach mode,
```suggestion
- Allow running `$ dune exec` in watch mode (with the `-w` flag). In watch mode,
```

2023-02-21 03:42 UTC, snowleopard commented on src/dune_console/dune_console.ml
> +  (* forget that [print_user_message] has ever been called *)
```suggestion
  (* forget that [print_user_message] has ever been called *)
  first_msg := true;
```

2023-02-21 04:00 UTC, snowleopard commented on src/dune_console/dune_console.ml
> +  (* forget that [print_user_message] has ever been called *)
```suggestion
  (* forget that [print_user_message] has ever been called *)
  first_msg := true;
```

2023-02-21 04:02 UTC, snowleopard approved these changes
Thanks! It's great that this feature is now compatible with the file-watching mode.

I wonder if `--separate-error-messages` is still the right name for the flag though. It now affects all messages, not just error messages, so perhaps it should be called `--separate-messages`? I don't have a strong opinion about this.

2023-02-21 04:18 UTC, rgrinberg commented
Thanks for taking a look. I'll rebase and merge.

> It now affects all messages, not just error messages, so perhaps it should be called --separate-messages? I don't have a strong opinion about this.

I'll call it `--display-separate-messages`.  Without the "display', it's not clear which part of dune this is affecting exactly.

2023-02-21 11:34 UTC, esope commented
Thanks. I will rename the flag as soon as possible.

2023-02-21 14:47 UTC, rgrinberg commented
I already did the rename

2023-02-21 14:48 UTC, merged

2023-02-22 12:46 UTC, esope commented
Great! Thanks!
I am eager to hear the feedback from users of JaneStreet and Tarides.
@gasche : should I/you try to implement the "blank line separation" on the OCaml compiler side?

2023-02-22 12:49 UTC, gasche commented
I proposed something like this yesterday in https://github.com/ocaml/ocaml/pull/12024

This is a bit harder to do on the compiler side because we don't have a generic abstraction of "message", we have the "reports" (errors and warnings) that are easy to handle, and a ton of other ad-hoc printing calls that would each need proper logic to be handled as messages. The PR above is a first iteration that does a good enough job, I hope.

2023-02-24 05:32 UTC, gasche commented
The compiler PR has been merged thanks to a careful review of @Octachron. Blank lines for everyone!

2023-02-24 07:33 UTC, snowleopard commented
Amazing, thanks @gasche! Great to see such tight collaboration between compiler and build system devs.