fix(stdlib): pass flags when building stdlib.ml
ocaml/dune pull request #7241
Opened 2023-03-08 14:37 UTC by emillon

Reported by @gretay-js.

This ensures that when building `stdlib.ml` (the main module of a library with `(stdlib)`), flags set in the corresponding stanza `(library)` are correctly passed.

2023-03-08 14:39 UTC, emillon commented
I'm not sure how to add that to the test suite. To do that locally, I added `(ocamlopt_flags :standard -alert +sample-alert)` to the test in `stdlib-compilation.t` and checked that it's passed in the log, but that's not great.
Also @rgrinberg I'm not too sure how related this fix is to the comment just above so maybe there's a better fix. Thanks!

2023-03-08 16:05 UTC, anmonteiro commented
@emillon I recently added some stdlib tests in https://github.com/ocaml/dune/pull/7139, perhaps that could be helpful.

2023-03-08 20:23 UTC, anmonteiro commented on src/dune_rules/compilation_context.ml
> +    | None ->
```suggestion
    match with_flags with
    | true -> t.flags
    | false ->
```

2023-03-08 20:23 UTC, anmonteiro commented on src/dune_rules/compilation_context.ml
> +let for_alias_module t ?flags alias_module =
```suggestion
let for_alias_module t ?(with_flags=false) alias_module =
```

2023-03-08 20:23 UTC, anmonteiro commented on src/dune_rules/compilation_context.ml
> +let for_alias_module t ?flags alias_module =
I think it'd be better if this didn't take flags from the outside, since the only use case is to use the flags from the compilation context itself.

2023-03-08 20:24 UTC, anmonteiro commented on src/dune_rules/module_compilation.ml
> +              Compilation_context.for_alias_module cctx m ~flags
```suggestion
              Compilation_context.for_alias_module cctx m ~with_flags:true
```

2023-03-08 23:26 UTC, rgrinberg requested changes

2023-03-08 23:26 UTC, rgrinberg commented on src/dune_rules/module_compilation.ml
> +              Compilation_context.for_alias_module cctx m ~flags
Seems weird to pass a flag to Compilation_context that's coming from the Compilation_context

2023-03-09 09:53 UTC, emillon commented
Thanks. I added a test and implemented your suggestions. I didn't realize it was coming from the same value.

2023-03-13 12:49 UTC, emillon commented on src/dune_rules/compilation_context.ml
> +let for_alias_module t ?(keep_flags = false) alias_module =
done

2023-03-13 15:46 UTC, rgrinberg approved these changes

2023-03-13 15:51 UTC, emillon commented on src/dune_rules/compilation_context.ml
> +    if keep_flags then t.flags
what about the following comment - is this related?

https://github.com/ocaml/dune/blob/35e3958215e0fed860aecb24e977a46448950103/src/dune_rules/module_compilation.ml#L486-L490

2023-03-13 17:30 UTC, rgrinberg commented on src/dune_rules/compilation_context.ml
> +    if keep_flags then t.flags
Yes, it's related but it's not quite the same. I think the main distinction is that:

1. For normal libraries, the alias module is generated. Therefore, there's no need to let the user control the flags on it. We know exactly how it should be compiled.
2. For the stdlib, the alias module is written by the user. Therefore, we need to give the user some control to modify the flags if necessary.

2023-03-14 09:06 UTC, emillon commented on src/dune_rules/compilation_context.ml
> +    if keep_flags then t.flags
Thanks.

2023-03-14 09:08 UTC, merged