Add note about monorepo benchmark to hacking doc
ocaml/dune pull request #7361
Opened 2023-03-21 03:21 UTC by gridbugs

2023-03-21 16:31 UTC, christinerose requested changes

2023-03-21 16:31 UTC, christinerose commented on doc/hacking.rst
> +benchmarking dune building a large monorepo constructed with
```suggestion
The file bench/monorepo/bench.Dockerfile sets up a Docker container for
benchmarking Dune building a large monorepo constructed with
```

2023-03-21 16:31 UTC, christinerose commented on doc/hacking.rst
> +the benchmark is a json string in the format accepted by `current-bench
```suggestion
the benchmark is a JSON string in the format accepted by `current-bench
```

2023-03-22 00:48 UTC, christinerose approved these changes

2023-03-22 02:19 UTC, Alizter commented
I think some more details are needed about which docker commands to run after building the image.

2023-03-22 04:19 UTC, gridbugs commented
I fixed an issue with the benchmarks where if a _build directory was present inside bench/monorepo `make bench` would fail. This was the problem @Alizter ran into above.

I've also added the full docker commands I use to build and run the image.

2023-03-22 12:03 UTC, Alizter approved these changes

2023-03-22 12:04 UTC, merged