doc: add some info about writing docs
ocaml/dune pull request #7537
Opened 2023-04-12 11:55 UTC by emillon

2023-04-12 15:52 UTC, christinerose requested changes
The opam team has verified it should be lowercase like this unless in a title or beginning of sentence.

2023-04-12 15:52 UTC, christinerose commented on doc/hacking.rst
> +- **opam**. Can be capitalised as Opam. The command is ``opam``.
```suggestion
- **opam**. Can be capitalised as Opam in titles and at the beginning of sentences only, as the official name is formatted opam. The command is ``opam``.
```

2023-04-14 03:50 UTC, christinerose commented on doc/hacking.rst
> +- **Dune** is the project, ``dune`` is the command. Files are called Dune files.
Nice catch! I was told back when I started working on the Dune project, that `dune` files were in mono space as well as the command `dune`. Dune is the project and when talking about the Dune tool in general. :)

2023-04-14 08:20 UTC, emillon commented on doc/hacking.rst
> +- **Dune** is the project, ``dune`` is the command. Files are called Dune files.
right, let's go with ``dune`` files.

2023-04-14 08:31 UTC, merged