feature: warn if modules is missing any mentioned modules
ocaml/dune pull request #7608
Opened 2023-04-21 22:55 UTC by Alizter

We warn the user if modules_without_implementation, private_modules or
virtual_modules contains any modules not in the modules field.

Fixes https://github.com/ocaml/dune/issues/7026

This will be made into an error in 3.9.

2023-04-22 03:40 UTC, rgrinberg requested changes
This warning should be ignored for vendored directories.

2023-04-23 17:58 UTC, Alizter commented
I've allowed the warning to be ignored when appearing inside a vendored directory and checked the vendored_dirs cases in each of the tests.

2023-04-24 18:59 UTC, rgrinberg commented on src/dune_rules/modules_field_evaluator.mli
> +  -> is_vendored:bool
We're already passing src_dir. Can we check if it's vendored inside eval?

2023-04-24 19:00 UTC, rgrinberg commented on src/dune_rules/modules_field_evaluator.ml
> +    (* Checking that (modules) incldues all declared modules *)
`includes.

2023-04-24 19:00 UTC, rgrinberg commented on src/dune_rules/modules_field_evaluator.ml
> +      if is_vendored then ()
`if not is_vendored ...`

2023-04-24 20:12 UTC, rgrinberg commented on src/dune_rules/modules_field_evaluator.mli
> +  -> is_vendored:bool
I don't see an issue with that.

2023-04-25 01:49 UTC, rgrinberg approved these changes

2023-04-28 18:25 UTC, Alizter commented
@rgrinberg merging this when the CI is green.

2023-04-28 20:33 UTC, merged