bug(pkg): Add reproduction case for `cat` not working due to wrong `PATH`
ocaml/dune pull request #8325
Opened 2023-08-02 13:10 UTC by Leonidas-from-XIV

I ran across this case in #8225 and thought I can extract that into a free-standing example so we can fix it and have a regression test.

2023-08-02 13:12 UTC, Leonidas-from-XIV commented
I think we discussed a similar issue with @Alizter and @gridbugs before.

2023-08-02 15:21 UTC, rgrinberg commented on test/blackbox-tests/test-cases/pkg/path.t
> +  > (=ↀωↀ=)✧  ヾ(*ΦωΦ)ﾉ
Let's stick to ascii if you don't mind

2023-08-03 06:48 UTC, gridbugs requested changes

2023-08-03 06:48 UTC, gridbugs commented on test/blackbox-tests/test-cases/pkg/path.t
> +  /usr/bin/sh: line 1: cat: command not found
This line is different on my machine:
```diff
-  /usr/bin/sh: line 1: cat: command not found
+  /bin/sh: cat: command not found
```

2023-08-03 06:48 UTC, gridbugs commented on test/blackbox-tests/test-cases/pkg/path.t
Can you name this file something more specific. To run this test manually the command is `dune build @test/path` which is very vague and likely to collide with another future test in another directory.

2023-08-03 06:57 UTC, gridbugs commented
In `pkg_rules.ml` if the `build_env` function returns an env containing a `PATH` it clobbers the `PATH` variable pulled from the user's environment. I guess we need to start extending the variable adding additional paths instead.

2023-08-03 08:59 UTC, rgrinberg commented on test/blackbox-tests/test-cases/pkg/path.t
> +  /usr/bin/sh: line 1: cat: command not found
Indeed, we can use `command` to make the test a little more resilient. Taken from stack overflow:

```
command -v cat >/dev/null 2>&1 || { echo "no cat" }
```

2023-08-03 09:03 UTC, Leonidas-from-XIV commented on test/blackbox-tests/test-cases/pkg/path.t
> +  > (=ↀωↀ=)✧  ヾ(*ΦωΦ)ﾉ
Sure, done!

2023-08-03 09:13 UTC, Leonidas-from-XIV commented on test/blackbox-tests/test-cases/pkg/path.t
Sure. Now that I opened the PR I can just name it after the PR number, so people can refer back to this discussion if they're confused :+1: as is the case with a few of our existing tests

2023-08-03 10:22 UTC, merged

2023-08-08 13:43 UTC, Leonidas-from-XIV commented
To conclude, for future readers: this issue has been fixed by #8333. Thanks @gridbugs!