refactor: remove markdown from terminal output
ocaml/dune pull request #9064
Opened 2023-11-01 19:12 UTC by rgrinberg

No terminal renders it. It has its own meaning in shell commands
(command substitution). I've added `$` to signify that it's a shell
command plus an underline for visual distinction.

Signed-off-by: Rudi Grinberg <me@rgrinberg.com>

2023-11-02 02:00 UTC, gridbugs requested changes
I like the idea of this change but I argue in favour of explicit quoting rather than using underlines to denote commands. Not all shells use `$` as their prompt (new macos uses zsh as its shell by default and I think the prompt is `%`) and `User_message.command` will be useful for formatting partial commands (e.g. `no such command 'foo'`) and in those cases adding a prompt would be misleading. The underline won't survive copy/pasting into some text fields which is definitely a use case we want to support.

Some points of comparison from other tools:

```
$ cargo foo
error: no such command: `foo`

        Did you mean `doc`?

        View all installed commands with `cargo --list`

$ opam foo
[NOTE] External dependency handling not supported for OS family 'nixos'.
       You can disable this check using 'opam option --global depext=false'
opam: unknown command `foo'.
Usage: opam COMMAND ...
Try `opam --help' for more information.

$ git foo
git: 'foo' is not a git command. See 'git --help'.

The most similar command is
        hook

$ npm foo
Unknown command: "foo"

To see a list of supported npm commands, run:
  npm help

$ nix foo
error: 'foo' is not a recognised command
       Did you mean one of fmt or log?
Try 'nix --help' for more information.
```

My personal preference is still backticks because I think its meaning has transcended markdown and shell to denote commands or code in general.

2023-11-02 07:36 UTC, rgrinberg commented
What I particularly dislike about the markdown style is that it already overlaps with a shell construct: command substitution. I've carelessly pasted such snippets into my shell and had to make sure that I didn't execute anything unwanted.

If you like quoting, the other quotation mechanisms don't suffer from this problem. Single, double, or emacs (as opam does) quotes are fine by me.

2023-11-02 07:39 UTC, rgrinberg commented on otherlibs/stdune/src/user_message.ml
> +  Pp.seq (Pp.verbatim "$ ") (Pp.tag (Style.Ansi_styles [ `Underline ]) @@ Pp.verbatim cmd)
I've added emacs style quotes tentatively.

2023-11-02 07:50 UTC, rgrinberg commented on src/dune_pkg/lock_dir.ml
> +            |> Pp.hovbox
Without it, the multiple in `hints` are going to be interpreted as separate lines.

2023-11-02 10:31 UTC, Leonidas-from-XIV approved these changes
I think this is fine (although I am personally not a fan of the m4 style asymmetric quotes, it always seemed wrongly formatted to my 00ies developer sensibilities), what would be a good improvement is to look through the code and use this everywhere, so we don't have yet another different convention.

In a quick search I found `coq_path.ml`, (possibly) `expander.ml`, `dune_file_watcher.ml`, `install_uninstall.ml`, `subst.ml` and `exec.ml` but I assume there are more places where commands are mentioned.

2023-11-02 23:23 UTC, gridbugs approved these changes
I agree with @Leonidas-from-XIV about the `<backtick>...'` quotes. To me they look old-fashioned. My personal preference would be to use  `'...'`.

2023-11-03 00:31 UTC, rgrinberg commented
It's single quotes now

2023-11-03 02:33 UTC, merged