Added rudimentary check on package names in dependencies
ocaml/dune pull request #9385
Opened 2023-12-05 10:48 UTC by ElectreAAS

Resolves #9270.

This PR adds a simple check to all the `<pkgname>` listed in the dependencies of a `dune-project`.

I just saw #9371, and have no opinions on it, but since they look closely related, I'm linking it here too.

Pinging @Leonidas-from-XIV & @emillon for a review.

2023-12-05 11:07 UTC, Leonidas-from-XIV requested changes
Great to have your first PR! I've added a few comments, convenient that there are already some cram tests to test the change.

2023-12-05 11:07 UTC, Leonidas-from-XIV commented on test/blackbox-tests/test-cases/invalid-package-version.t
>  Building doesn't raise any error about the invalid version.
This should be updated now.

2023-12-05 11:07 UTC, Leonidas-from-XIV commented on test/blackbox-tests/test-cases/invalid-package-version.t
>  Even generating .opam files doesn't raise any error about the version.
Likewise.

2023-12-05 13:38 UTC, ElectreAAS commented on src/dune_rules/package.ml
> +       | _ -> true)
Realized a bit late that `decode_name` in the same file already does the same thing, I just needed to a bit of glue in between.

2023-12-05 13:40 UTC, ElectreAAS commented
Note: I only added the 'opam compatible' check in the `depends` field, but not the similarly formed `conflicts` and `depopts`. For the latter it seems to make sense, but the former?

2023-12-05 15:38 UTC, Alizter commented
@ElectreAAS We use `conflicts` as inputs to the solver IIRC so they should also be validated the same as `depends`.

2023-12-06 10:02 UTC, ElectreAAS commented
I just rebased the PR on main, sorry for the noise.

I have updated the expect part of [test/blackbox-tests/test-cases/pkg/invalid-version.t](https://github.com/ElectreAAS/dune/blob/main/test/blackbox-tests/test-cases/pkg/invalid-version.t), but not the text yet, as I'm quite confused as to what is the difference in tested behaviour in this test and [test/blackbox-tests/test-cases/invalid-package-version.t](https://github.com/ElectreAAS/dune/blob/main/test/blackbox-tests/test-cases/invalid-package-version.t).

2023-12-08 10:25 UTC, Leonidas-from-XIV commented
However should we care about `(depends)` if we're not generating opam files and never use the data?

Not sure how many packages specify depends without generating opam files, because without it it is fairly pointless at the moment.

2023-12-12 15:03 UTC, closed without merging