fix(boot): make bootstrap reproducible by default
ocaml/dune pull request #9563
Opened 2023-12-22 13:33 UTC by emillon

Fixes #9507

In `duneboot.ml`, there are 2 strategies to build `dune.exe`:
- separate compilation (build all modules and link them together in several commands)
- single command compilation (pass all modules to the compiler driver)

Separate compilation can be executed in parallel when `-j` is set accordingly, which speeds up the build.
But when only one job can be executed at once (`-j 1`), it is faster to use a single command.

So, we would switch to single command build when `-j 1` was passed. However, this is surprising because it produces a different binary depending on the number of parallel jobs (see #9507). So this disables this optimization by default; it can be enabled by hand by passing `--use-single-command`.

(NB: this does not apply to Windows, which always uses single command compilation)

2023-12-22 18:17 UTC, rgrinberg approved these changes
LGTM, but I think a name like `--build-single-command` is more appropriate. "use" is a bit too general, and we're still allowed to run `ocamldep` with multiple commands (for example)

2023-12-22 18:17 UTC, rgrinberg commented on boot/duneboot.ml
> +  let use_single_command = ref Sys.win32 in
Could you leave a comment to explain why windows is special?

2023-12-22 18:17 UTC, rgrinberg commented
a CHANGES entry is necessary as well please

2023-12-22 18:20 UTC, rgrinberg requested changes
Actually, don't you need to accept (and ignore) this argument in `boot/bootstrap.ml`? Otherwise it will complain that the argument is unknown and won't display it in `ocaml bootstrap.ml --help`.

2024-01-15 16:06 UTC, emillon commented
Closed in favor of #9735.

2024-01-15 16:06 UTC, closed without merging